# Generated by Django 5.0 on 2026-09-26 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría del blog',
                'verbose_name_plural': 'Categorías del blog',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta del blog',
                'verbose_name_plural': 'Etiquetas del blog',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'Prefiero no indicar')], max_length=1)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('ND', 'No determinado')], default='ND', max_length=3)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=12)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=12)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='store.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('PSICOLOGIA', 'Psicología'), ('PSICOLOGIA_CLINICA', 'Psicología Clínica'), ('TERAPIA_FAMILIAR', 'Terapia Familiar'), ('TERAPIA_PAREJA', 'Terapia de Pareja'), ('OTRA', 'Otra')], default='PSICOLOGIA_CLINICA', max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='store.profesional'),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('evaluacion', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('intervencion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('plan_seguimiento', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_clinicos', to='store.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='store.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='store.profesional')),
            ],
            options={
                'verbose_name': 'Historia clínica',
                'verbose_name_plural': 'Historias clínicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='store.profesional'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10)),
                ('meta_titulo', models.CharField(blank=True, max_length=200)),
                ('meta_descripcion', models.CharField(blank=True, max_length=300)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_blog', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='store.categoriablog')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='posts', to='store.etiquetablog')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-fecha_publicacion', '-creado_en'],
                'indexes': [models.Index(fields=['estado', '-fecha_publicacion'], name='store_post_estado_36f490_idx'), models.Index(fields=['slug'], name='store_post_slug_e52358_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellidos', 'nombres'], name='store_pacie_apellid_5d5c96_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='store_pacie_estado_665812_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['paciente', '-fecha'], name='store_histo_pacient_050eab_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='store_cita_fecha_h_fbb779_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'fecha_hora'], name='store_cita_profesi_c6c29b_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha_hora'], name='store_cita_pacient_5ac6e3_idx'),
        ),
    ]
